require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.3.4
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  CountAsOne: ['array', 'method_call']
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: never

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template
