---
version: "3.8"

services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    working_dir: /app
    container_name: app
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle

volumes:
  rubygems:
  db:
